import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import * as XLSX from "xlsx";

import type { StoresDatabase } from "../stores/database";
import { PlanningDatabase } from "./database";
import type { PlanningExportInput, PlanningExportResult, RestockPlanningItem } from "./types";

const SCHEMA_VERSION = "3.0";

function timestampForFile(): string {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function csvCell(value: unknown): string {
  const text = String(value ?? "");
  return /[",\n\r]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

function toCsv(rows: Array<Record<string, unknown>>): string {
  if (rows.length === 0) return "Schema Version\n3.0\n";
  const headers = Object.keys(rows[0]);
  return [
    headers.map(csvCell).join(","),
    ...rows.map((row) => headers.map((header) => csvCell(row[header])).join(",")),
  ].join("\n");
}

function orderQuantity(item: RestockPlanningItem): number {
  return item.approvedOrderQuantity ?? item.suggestedOrderQuantity;
}

export class PlanningExporter {
  constructor(
    private readonly planning: PlanningDatabase,
    private readonly stores: StoresDatabase,
  ) {}

  generate(input: PlanningExportInput): PlanningExportResult {
    const statuses = input.statuses?.length ? input.statuses : ["APPROVED"];
    const state = this.planning.getState();
    const selected = state.items.filter((item) =>
      statuses.includes(item.recommendationStatus as "REVIEWED" | "APPROVED")
      && orderQuantity(item) > 0,
    );
    if (selected.length === 0) {
      throw new Error("No reviewed or approved restock recommendations with a positive order quantity are ready to export.");
    }

    // Reuse the same validated backup lifecycle used by Tally exports.
    this.stores.backup("before-restock-export");

    const createdAt = new Date().toISOString();
    const batchId = randomUUID();
    const folder = this.stores.getState().database.exportFolder;
    mkdirSync(folder, { recursive: true });
    const prefix = `inventory-scanner-planning-v${SCHEMA_VERSION}-${timestampForFile()}`;
    const excelPath = path.join(folder, `${prefix}-restock.xlsx`);
    const csvPath = input.includeCsv ? path.join(folder, `${prefix}-tally-reorder.csv`) : null;

    const tallySelected = selected.filter((item) => item.catalogSource === "TALLY");
    const localSelected = selected.filter((item) => item.catalogSource === "LOCAL");
    const tallyRows = tallySelected.map((item) => ({
      "Schema Version": SCHEMA_VERSION,
      "Tally Stock Item Name": item.itemName,
      "Tally Stock Item GUID": item.tallyItemGuid,
      "Reorder Level": item.reorderPoint,
      "Minimum Order Quantity": item.minimumOrderQuantity,
      "Approved Purchase Quantity": orderQuantity(item),
      "Preferred Supplier": item.preferredSupplierName,
      "Planning Note": item.notes,
    }));
    const localRows = localSelected.map((item) => ({
      "Schema Version": SCHEMA_VERSION,
      "Local Stores Catalog Item": item.itemName,
      Group: item.groupName,
      "Approved Purchase Quantity": orderQuantity(item),
      "Reorder Level": item.reorderPoint,
      "Target Stock": item.targetStock,
      "Preferred Supplier": item.preferredSupplierName,
      Note: "Local-only item; create or map this Stock Item in Tally before import.",
    }));
    const reviewRows = selected.map((item) => ({
      "Schema Version": SCHEMA_VERSION,
      "Stock Item": item.itemName,
      "Catalog Source": item.catalogSource,
      Group: item.groupName,
      "On Hand": item.onHand,
      Reserved: item.reserved,
      "Service Reserve": item.serviceReserve,
      Available: item.available,
      Incoming: item.incoming,
      Projected: item.projected,
      "Reorder Point": item.reorderPoint,
      "Usage Suggested Reorder Point": item.suggestedReorderPoint,
      "Target Stock": item.targetStock,
      "Suggested Order": item.suggestedOrderQuantity,
      "Approved Order": orderQuantity(item),
      "Minimum Order Quantity": item.minimumOrderQuantity,
      Supplier: item.preferredSupplierName,
      "Configured Lead Time Days": item.leadTimeDays,
      "Effective Lead Time Days": item.effectiveLeadTimeDays,
      "Observed Median Lead Time Days": item.observedLeadTimeMedianDays ?? "",
      Status: item.recommendationStatus,
      Health: item.health,
    }));
    const metadataRows = [
      { Field: "Export Schema", Value: SCHEMA_VERSION },
      { Field: "Batch ID", Value: batchId },
      { Field: "Generated At", Value: createdAt },
      { Field: "Generated By", Value: input.exportedBy ?? "" },
      { Field: "Tally Mapping", Value: "Map 'Tally Stock Item Name', 'Reorder Level', and 'Minimum Order Quantity' in TallyPrime's Excel import template." },
      { Field: "Direct Tally Posting", Value: "Disabled; this is a reviewable/manual import file." },
    ];

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(metadataRows), "Metadata");
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(reviewRows), "Restock Review");
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(tallyRows), "Tally Reorder Import");
    if (localRows.length > 0) {
      XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(localRows), "Local-only Restock");
    }
    XLSX.writeFile(workbook, excelPath, { compression: true });
    if (csvPath) writeFileSync(csvPath, toCsv(tallyRows), "utf8");

    const payloadHash = createHash("sha256").update(JSON.stringify({ tallyRows, localRows })).digest("hex");
    this.planning.recordExportBatch({
      id: batchId,
      createdAt,
      createdBy: input.exportedBy ?? "",
      excelFilename: path.basename(excelPath),
      csvFilename: csvPath ? path.basename(csvPath) : "",
      itemCount: selected.length,
      payloadHash,
    });
    this.planning.markRecommendationsExported(selected.map((item) => item.stockItemId), createdAt);

    return {
      schemaVersion: SCHEMA_VERSION,
      batchId,
      excelPath,
      csvPath,
      itemCount: selected.length,
      warnings: [
        "Tally reorder settings are exported as an Excel/CSV mapping file. Direct master alteration remains disabled.",
        ...(localRows.length > 0
          ? [`${localRows.length} local-only Stores Catalog item${localRows.length === 1 ? " was" : "s were"} excluded from the Tally import sheet and listed separately.`]
          : []),
      ],
    };
  }
}
